### ISSUE TITLE
Python is an unmentioned dependency

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/nahmii-cli#22]
As reported by @markbkk in #21

**Comment by liamaharon** [comment]
Yeap, makes sense to add it to the readme

**Comment by ValKos** [comment]
Hello there!
Have python 3/7/0. NPM 5/6/0. NODEJS 8.11.3. node-gyp@3.8.0
But still failed to install striim-cli

[2018-09-11T06_04_02_939Z-debug.log](https://github.com/hubiinetwork/striim-cli/files/2369507/2018-09-11T06_04_02_939Z-debug.log)
[2018-09-11T06_04_08_311Z-debug.log](https://github.com/hubiinetwork/striim-cli/files/2369508/2018-09-11T06_04_08_311Z-debug.log)

.

**Comment by morfj** [comment]
@markbkk are you able to install it on your Windows machine, or are you getting the same error as @ValKos ?

Are you installing the whole thing, or doing the "minimum install" of striim BTW? (what is the install command you are running?)

**Comment by ValKos** [comment]
@morfj Personally I have managed to install striim through windows git bash. So, resolved.

**Comment by morfj** [comment]
Very often node GYP errors (especially on Windows) are related to incorrect or missing environment settings (like the path to where your python libs are, or your compiler, etc). The error messages resulting from those type of issues are cryptic at the best of days :P
