### ISSUE TITLE
Deposit tx being mined not detected by CLI

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/nahmii-cli#33]
When making an ETH deposit via the CLI, it will be 'pending' until it times out, but if I visit etherscan I can see that the tx completed >1m ago.

```
liam@carl:~$ nahmii deposit 0.01 ETH
............................................................Error: Cannot read property 'message' of undefined

```

Token deposits also fail. The first 'approve' tx will be mined, but the second tx will never be sent to the client fund SC.

```
liam@carl:~$ nahmii deposit 0.01 BOKKY
............................................................Error: Deposit failed: Failed to approve ERC20 token payment in time!
```

![screenshot from 2018-10-09 13-20-58](https://user-images.githubusercontent.com/16665596/46643076-37818b80-cbc6-11e8-9c4d-51b834893662.png)

**Comment by liamaharon** [comment]
I guess this is probably related to our node being down? If so we can close it

**Comment by morfj** [comment]
Can you retest it in the same conditions @liamaharon ?

**Comment by liamaharon** [comment]
Working now :+1:
